apiVersion: v1
kind: Service
metadata:
  name: reds-mongo
spec:
  selector:
    app: reds-mongo
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reds-mongo
spec:
  selector:
      matchLabels:
        app: reds-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: reds-mongo
    spec:
      containers:
        - name: reds-mongo
          image: reds-mongo
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap 
                  key: host
                  
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
               secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
               secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password     
                
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-ingress
spec:
  rules:
  - host: reds-mongo.minikube.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reds-mongo
            port:
              number: 8080
                
 
